# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/pagarme/secbot
    steps:
      - checkout
#      - run:
#          name: go get secbot repository
#          command: go get github.com/pagarme/secbot
      - run:
          name: Sonar Stuff
          command: |
            wget -c https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
            unzip sonar-scanner-cli-3.2.0.1227-linux.zip
            cd sonar-scanner-3.2.0.1227-linux/
            ./bin/sonar-scanner -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.projectKey=$PROJECTKEY -Dsonar.host.url=$HOST_URL -Dsonar.sources=. -X
      - run:
          name: Quality Gate
          command: |
            curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python
            sudo pip install requests
            wget -c https://gist.githubusercontent.com/sfcardoso1/806b5bc90002317583bd29a277c5979f/raw/341c132d1763ce9e21577fcd3dfb8ddb2129da9d/fefs.py
            python fefs.py
