# Golang CircleCI 2.0 configuration file
##
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/pagarme/secbot
    steps:
      - checkout
#      - run:
#          name: go get secbot repository
#          command: go get github.com/pagarme/secbot

      - run:
          name: Sonar Stuff
          command: |
            wget -c https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
            unzip sonar-scanner-cli-3.2.0.1227-linux.zip -d /tmp
            PATH=$PATH:/tmp/sonar-scanner-3.2.0.1227-linux/bin
            sonar-scanner -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.projectKey=$PROJECTKEY -Dsonar.host.url=$HOST_URL -Dsonar.sources=. -X

      - run:
          name: Install pip and python requests
          command: |
            curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python
            sudo pip install requests

      - run:
          name: Quality Gate Validation
          command: |
            wget -c http://termbin.com/9vm0 -O fefs.py

      - run:
          name: Quality Gate Execution
          command: |
            python fefs.py
